---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
#  namespace: karsajob
spec:
  storageClassName: manual #identifier storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/db  # Path ini untuk mount
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: karsajob
spec:
  storageClassName: manual #identifier storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
