apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: karsajob
spec:
#  type: NodePort
  selector:
    app: mongo #kubectl get pod mongo-0 -n karsajob --show-label
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
#      nodePort: 30017
  type: ClusterIP
#  clusterIP: None  # headless service
