apiVersion: v1
kind: Secret            #jenis service secret (biasanya untuk data credential)
metadata:
  name: mongo-secret    #nama service secret
  namespace: karsajob   #nama namespace/group
type: Opaque
data:
  MONGO_ROOT_USERNAME: YWRtaW4= #admin (data variable)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  #supersecretpassword (data variable)
