apiVersion: v1
kind: Service          #jenis service service
metadata:
  name: mongo          #nama service
  namespace: karsajob  #nama namespace/group
spec:
#  type: NodePort
  selector:
    app: mongo #kubectl get pod mongo-0 -n karsajob --show-label
  ports:  #alamat port(default mongo)
    - protocol: TCP
      port: 27017
      targetPort: 27017
#      nodePort: 30017
  type: ClusterIP
#  clusterIP: None  # headless service
