services:
  item-app:
    image: rakafd/item-app:v1  # namaimage
#    ports:
#      - "80:80" #remap port 80 karena untuk port 80 sudah dipakai nginx saya sebelumnya tapi saya matikan sementara
    depends_on:
      - item-db #menunggu untuk service item-db
    restart: always #untuk selalu menjalankan ulang

  item-db:
    image: mongo:3 #image mongo
    volumes:
      - app-db:/data/db #volum yang diarahkan ke /data/db
    restart: always #untuk selalu menjalankan ulang

volumes:
  app-db: