services:
  item-app:
    image: ghcr.io/rakafde/item-app:v1  # namaimage berdasarkan github package
    ports:
      - "80:8080" #remap port host port 80 containerport 8080
    depends_on:
      - item-db #menunggu untuk service item-db
    restart: always #untuk selalu menjalankan ulang

  item-db:
    image: mongo:3 #image mongo
    volumes:
      - app-db:/data/db #volum yang diarahkan ke /data/db
    restart: always #untuk selalu menjalankan ulang

volumes:
  app-db: