#config circle ci
version: 2.1 #versi circleci

#pakai orb circleci, seperti contoh di dokumentasi web circleci

orbs:
  docker: circleci/docker@3.0.1

#job / task
jobs:
#  lint-dockerfile-backend: #job untuk lint bnackend
#    docker:
#      - image: hadolint/hadolint:latest
#    steps:
#      - checkout
#      - run:
#          name: proses lint backend #nama proses/job
#          command: hadolint backend/Dockerfile #target file backend lint
#-------------------------------------------

#  lint-dockerfile-frontend: #lint frontend
#    docker:
#      - image: hadolint/hadolint:latest
#    steps:
#      - checkout
#      - run:
#          name: proses lint frontend
#          command: hadolint frontend/Dockerfile
#------------------------------------------

  test-backend: #job gotest
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run:
          name: unit test go
          command: go test -v -short --count=1 $(go list ./backend/...) # go test
#------------------------------------------

  build-frontend: #job untuk build & push imag frontend
    docker:
      - image: cimg/base:stable #base image circleci
    steps:
      - checkout 
      - setup_remote_docker #mengaktifkan env docker pada circleci untuk build image
      - run:
          name: build dan push image frontend #nama pada dasboard
          command: | #kumpulan perintah untuk dirun
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
            FULL_IMAGE_NAME="ghcr.io/${GITHUB_USERNAME}/karsajob-ui:latest"
            docker build -t "$FULL_IMAGE_NAME" ./frontend
            docker push "$FULL_IMAGE_NAME"
#---------------------------------------------------

  build-backend: #job untuk build dan push image baceknd
    docker:
      - image: cimg/base:stable #base image circleic
    steps:
      - checkout
      - setup_remote_docker #mengaktifkan env docker pada circleci untuk build image
      - run:
          name: build dan push image backend #nama pada dashboard
          command: | #kumpulan perintah untuk dirun
            echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
            FULL_IMAGE_NAME="ghcr.io/${GITHUB_USERNAME}/karsajobs:latest"
            docker build -t "$FULL_IMAGE_NAME" ./backend
            docker push "$FULL_IMAGE_NAME"
#=======================================================================
#=======================================================================

#workflow untuk mengatur urutan /kondisi jobs
workflows:
  version: 2
  dev-workflow:
    jobs:
      #Backend
      - docker/hadolint:
          name: lint-backend
          dockerfiles: backend/Dockerfile
          hadolint_tag: 2.12.0-debian
          filters: #filter branch
            branches:
              only: dev
#          paths: #filter path yang ada perubahan
#            only:
#              - backend/*
#              - .circleci/*

      - test-backend:
          requires:
            - lint-backend #proses workflow sebelumnya
          filters:
            branches:
              only: dev
#          paths:
#            only:
#              - backend/*
#              - .circleci/*

      - build-backend:
          requires:
            - test-backend
          filters:
            branches:
              only: dev
 #         paths:
 #           only:
 #             - backend/*
 #             - .circleci/*

#-------------
      #frontend
      - docker/hadolint:
          name: lint-frontend
          dockerfiles: frontend/Dockerfile
          hadolint_tag: 2.12.0-debian
          filters:
            branches:
              only: dev
 #         paths:
 #           only:
 #             - frontend/*
 #             - .circleci/*

      - build-frontend:
          requires:
            - lint-frontend
          filters:
            branches:
              only: dev
 #         paths:
 #           only:
 #             - frontend/*
 #             - .circleci/*
