apiVersion: v1
kind: Service            #jenis resource (service)
metadata:
  name: karsajobs        #nama service
  namespace: karsajob    #nama namespace / group
spec:
  type: NodePort         #jenis service (agar dapat di gunakan/akses dari luar cluster)
  selector:
    app: karsajobs       #selector untuk label, cocok/sesuaikan dengan label deploy,ent
  ports:
#    - protocol: TCP
    - port: 8080         #port service internal
      targetPort: 8080 #port yang dituju (port container deployment)
      nodePort: 30080  # pilih port antara 30000–32767, untuk diakses dari luar cluster

