apiVersion: v1
kind: Service            #jenis resource (service)
metadata:
  name: karsajobs-ui    #nama service
  namespace: karsajob   #nama namespace/grup
spec:
  type: NodePort        #jenis service node (agar bisa diakses/koneksi dari luar cluster)
  selector:
    app: karsajobs-ui   #selector untuk label, cocok/sesuaikan dengan label deployment
  ports:
    - port: 8000          #port internal
      targetPort: 8000  #port deployment
      nodePort: 30081   #port untuk diakses dari luar cluster range 30000-32767
